"""Routes for creating GitHub Pull Requests from generated patches."""

import logging

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db import get_db
from app.models import CreatePRRequest, CreatePRResponse
from app.models_db import User
from app.routes.auth import get_current_user
from app.services.github import (
    GitHubAPIError,
    commit_patches,
    create_branch,
    create_pull_request,
    get_branch_sha,
    get_default_branch,
    make_branch_name,
)

logger = logging.getLogger(__name__)

router = APIRouter(tags=["pr"])


@router.post("/create-pr", response_model=CreatePRResponse)
async def create_pr(
    req: CreatePRRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Create a GitHub PR from the provided patches."""
    if not user.github_repo_owner or not user.github_repo_name:
        raise HTTPException(
            status_code=400,
            detail="No GitHub repository indexed. Please index a GitHub repo first.",
        )

    try:
        token = user.get_access_token()
    except Exception:
        raise HTTPException(status_code=401, detail="Could not decrypt access token. Please log in again.")

    owner = user.github_repo_owner
    repo = user.github_repo_name

    try:
        base = req.base_branch or await get_default_branch(token, owner, repo)
        base_sha = await get_branch_sha(token, owner, repo, base)

        branch_name = make_branch_name(req.ticket_title)
        await create_branch(token, owner, repo, branch_name, base_sha)

        commit_msg = f"fix: {req.ticket_title}\n\nGenerated by AutoPatch AI"
        patches_data = [p.model_dump() for p in req.patches]
        await commit_patches(token, owner, repo, branch_name, patches_data, commit_msg)

        pr_body_parts = [f"## AutoPatch AI Fix\n\n**Ticket:** {req.ticket_title}"]
        if req.explanation:
            pr_body_parts.append(f"\n### Explanation\n\n{req.explanation}")
        pr_body_parts.append(f"\n### Files Changed\n")
        for p in req.patches:
            pr_body_parts.append(f"- `{p.file_path}`")

        pr_result = await create_pull_request(
            token, owner, repo,
            head=branch_name,
            base=base,
            title=f"fix: {req.ticket_title}",
            body="\n".join(pr_body_parts),
        )

        return CreatePRResponse(
            pr_number=pr_result["pr_number"],
            pr_url=pr_result["pr_url"],
            branch=branch_name,
        )

    except GitHubAPIError as e:
        status_map = {401: 401, 403: 403, 404: 404, 422: 409}
        raise HTTPException(
            status_code=status_map.get(e.status, 502),
            detail=str(e),
        )
    except Exception as e:
        logger.exception("Unexpected error creating PR")
        raise HTTPException(status_code=502, detail=f"Failed to create pull request: {e}")
